### ISSUE TITLE
Add support to display only for selected languages

### ISSUE THREAD

**Issue by Eldenroot** [Darth-Apple/BAM#11]
![image](https://user-images.githubusercontent.com/778890/74104136-1af6ba00-4b52-11ea-8cd3-50bae63cccb0.png)

Something like Jones H. plugin has... quite useful if you have English speaking and non English speaking users (lets say your native lang)

**Comment by Darth-Apple** [comment]
Added. Both features are now included in the next release. These will be unofficial features to avoid cluttering the settings, but BAM will support both if needed.

**Comment by Eldenroot** [comment]
@Darth-Apple thats great, thank you!
