### ISSUE TITLE
Custom CSS class bug

### ISSUE THREAD

**Issue by Eldenroot** [Darth-Apple/BAM#12]
![image](https://user-images.githubusercontent.com/778890/74104180-7628ac80-4b52-11ea-94d2-ec8e85276999.png)

When you choose "Style/Class/ to predefined class but you leave any text in the filed below -> it is ignored. You have to first delete the text and leave the field empty. It should be AJAX loaded, so when you select custom class -> show the extra field for css class

**Comment by Darth-Apple** [comment]
This is intended functionality from BAM 1.0, but it was very confusing for many users and there were frequent questions on how the feature worked. The new version will fix this by hiding the field if a predefined class is set.
