### ISSUE TITLE
Add start and end date for announcement

### ISSUE THREAD

**Issue by Eldenroot** [Darth-Apple/BAM#3]
Add start and end date for announcement

**Comment by ghost** [comment]
Again, this would be very helpful.

**Comment by Darth-Apple** [comment]
Will consider, thank you for the suggestion. Currently developing a new version, and I'll do my best to fit this one in!

**Comment by Eldenroot** [comment]
![image](https://user-images.githubusercontent.com/778890/74104239-f2bb8b00-4b52-11ea-8a30-0f8a16280744.png)

(screenshot taken from this plugin setting: https://community.mybb.com/mods.php?action=download&pid=134)

**Comment by Darth-Apple** [comment]
I have considered it. Unfortunately, this won't make it in the initial release of BAM 2.0, as I simply don't have time to get everything implemented and tested. This particular feature would require a lot of additional code and testing, so I'll likely add it to a follow up release once BAM 2.0 is released.
