### ISSUE TITLE
Add setting: Allow Random Mode announcements to Be displayed on other Pages.

### ISSUE THREAD

**Issue by Darth-Apple** [Darth-Apple/BAM#44]
BAM 1.0 allowed random mode announcements to be displayed either on the index page, or globally. BAM 2.0 more or less removed this as a side effect of the reorganization on how BAM's settings were laid out. 

I'm going to add this back in for 2.1. I'll also be addressing a few other things with Random mode to try to make it a little more clear and clean. 

Also, strongly considering removing the "enable or disable random mode" setting, and simply letting it always be enabled. It's completely unecessary in the new version, as random mode is now completely decoupled from standard mode (and exists on an entirely separate tab). Removing it would make space for some other (more useful) settings on the setting page and help decrease the bloat in the new version.

**Comment by Darth-Apple** [comment]
This is being closed for now. Will revisit this on future MyBB 1.9 port of BAM. MyBB 1.9 is still pre-beta, so development has not begun on BAM 3.

**Comment by BettyIsBoop** [comment]
In 2.0 : i use `index.php,forumdisplay.php,showthread.php` for index page settings.
It used for random mode

Thank you :)
