### ISSUE TITLE
Database error if using non-standard table prefix

### ISSUE THREAD

**Issue by ryanstubbs** [Darth-Apple/BAM#46]
This seems to mainly be down to the newest_member tag that's available.

Looks like the table name is hard-coded in the query so if you're using a different prefix, it throws an SQL error:

`function getNewestMember() {
    global $db;
    $querydata = $db->fetch_array($db->query('SELECT uid FROM mybb_users ORDER BY uid DESC LIMIT 1'));
    return get_user($querydata['uid']);
}`

**Comment by Darth-Apple** [comment]
Very good observation. Will be fixed ASAP, thank you. 

Surprised I didn't catch this during testing. I use a nonstandard prefix myself. In any case, it will be resolved shortly!

**Comment by Darth-Apple** [comment]
Fixed, thank you.
