### ISSUE TITLE
Add support for show/hide specific announcement globally/index/specific forum

### ISSUE THREAD

**Issue by Eldenroot** [Darth-Apple/BAM#5]

**Comment by ghost** [comment]
I remember when a plugin did this in 1.6. It was very helpful to be able to control it on a per announcement level.

**Comment by Eldenroot** [comment]
for now you can use mod from https://github.com/JN-Jones/Announcement

**Comment by ghost** [comment]
I will have to anyway; this plugin doesn't seem to work for me. Although it looks great, and would do what I need for the moment, the announcements simply won't display on my forum. The template is definitely correct and there are no other plugins except MyBB GoMobile... odd. I did submit a reply to the thread for it however with the authors last online time being 2015, I don't hold out much hope for a fix any time soon even if I posted it here too. I'll give that one a go, thanks. I hope it supports permissions.

**Comment by ghost** [comment]
Just tried that plugin and that one doesn't work either! Ugh!!

**Comment by Darth-Apple** [comment]
This feature is beyond the scope of this plugin. However, the upcoming version of this plugin does implement something like this in a new "Advanced Mode." As long as you have the link of the page to display an announcement on, the new version will give you much more granularity on where announements are dispalyed. 

Stay tuned for more. :)

**Comment by Eldenroot** [comment]
This is possible in this plugin (Jones H. - Announcement)

![image](https://user-images.githubusercontent.com/778890/74104215-ba1bb180-4b52-11ea-8ddb-43d68a16c4d3.png)

**Comment by Darth-Apple** [comment]
Yes, but I won't copy another developer's plugin. :)

Bam 2.0 enables this using links instead. Paste a link to a forum, or to a thread, and it will display on the corresponding pages!

**Comment by Eldenroot** [comment]
It is not copying first of all :)

Just wanted to give you an idea (and from where I got the screenshot), thats all...

**Comment by Darth-Apple** [comment]
Your exact suggestion has been implemented! The second beta will have a drop down for specific forums to display the announcement in.

 Advanced mode will still exist to allow announcements to be displayed on specific threads, profiles, etc. by pasting a link to the page, so if the forum selector does not give enough options on where to post, advanced mode will make up the difference.
