### ISSUE TITLE
Please, give a option to dismiss que announcement.

### ISSUE THREAD

**Issue by palhanow** [Darth-Apple/BAM#7]
The plugin is great, but i want to give a suggestion:

Can you implement the function for the member dismiss the announcement? Or a category for "dismissable announcement?"

And a option to "show again after X days after dismissed"?

Would be great. 

Thanks again.

**Comment by bio8674** [comment]
This feature has been heavily requested. I'm planning an updated version of this plugin later this year, and will implement this feature in the upcoming version!

**Comment by Darth-Apple** [comment]
I'm developing a new version that will be released in the next couple of months. This functionality has already been implemented in the new version!

**Comment by Eldenroot** [comment]
Yeah but there should be an option to "Display again in XXX days or minutes)

**Comment by Eldenroot** [comment]
And much more -> enable dismiss announcement only for specific usergroups

**Comment by Darth-Apple** [comment]
For your first suggestion, this feature is implemented! There is a new setting that configures how long BAM announcements remained dismissed. There is an optional "close only" mode as well, that only closes the announcements, but allows them to return later. 

For your second suggestion, this won't be implemented at this time. There is not enough time to implement and fully test this. Additionally, it would cause unexpected or confusing behavior if the dismissal permissions were different than the announcement's permissions itself. In short, it's a little harder to implement than it might seem at first glance. 

BAM 2.0 does have a setting that disables dismissals for guests, however. :)

**Comment by Eldenroot** [comment]
Wow, nice, that was fast.

Right now I use dismissing based on user cookies which are valid only for specified time period, after that the announcement is displayed again (yeah, it is not a bullet proof concept and depends hardly on cookies but it is only a workaround).

**Comment by Darth-Apple** [comment]
As a matter of fact, this is exactly what BAM 2.0 does. It saves expirable cookies (expiration time configurable) that prevents a dismissed announcement from displaying again. 

The only issue that remains to be solved is making sure that dismissed announcements don't get saved if BAM gets reinstalled. (As it stands now, this is one of the final bugs remaining in the new beta. This will, of course, be fixed before the release.)
