### ISSUE TITLE
Add support to display an announcement only for selected themes

### ISSUE THREAD

**Issue by Eldenroot** [Darth-Apple/BAM#8]

**Comment by Darth-Apple** [comment]
This feature is beyond the scope of this plugin, but this is a good suggestion. The upcoming version of this plugin does implement this feature as an unofficial addon in a new "Advanced Mode." It will now be possible to enable announcements to be displayed only on specific themes! 

Stay tuned for more. :)

**Comment by Eldenroot** [comment]
similar to #11

**Comment by Eldenroot** [comment]
Closed, implemented - see #11
