### ISSUE TITLE
Add enable/disable for every announcement 

### ISSUE THREAD

**Issue by Eldenroot** [Darth-Apple/BAM#9]

**Comment by Darth-Apple** [comment]
This is a great suggestion, but it will unfortunately most likely not be implemented. It is not technically difficult to put into place, but it would clutter the announcements settings page. Currently, disabling all usergroups for an announcement achieves the same result. 

May reconsider if there is enough demand for this feature. For the time being, this will not be added into the new version. Perhaps in a future release!

**Comment by Eldenroot** [comment]
Ouch, I would like to see this anyway. :)

It is posible right now in Jones H. plugin - Announcement (unfortunately, no active development)

![image](https://user-images.githubusercontent.com/778890/74104083-9e63db80-4b51-11ea-901e-72d4e8d33cd1.png)

Check the "dots" on the left...

**Comment by Darth-Apple** [comment]
Unfortunately, this won't make it in the new version. Perhaps in a future release!

**Comment by Darth-Apple** [comment]
This was now added as a new directive tag that you can put in the announcement's text! It wasn't a full enable/disable setting, but it gets the job done. A future release will likely complete this feature as a full setting. 

Focus is now on bug fixes and getting BAM ready for release. It's getting more stable, and is nearing completion very soon!
